ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "termsAcceptedAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "privacyVersion" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "guardianConsentAt" TIMESTAMP(3);
