const { test } = require('node:test');
const assert = require('node:assert/strict');
const vm = require('node:vm');
const fs = require('node:fs');
const path = require('node:path');
const origin = 'http://localhost';
const api = 'https://api.example.test/api';
const formula = { slug: 'test-formula', title: 'Нийлбэр', latex: 'a+b', general: 'a+b', explanation: 'Нийлбэрийг олно.', examples: [{ problem: '$1+2$', steps: ['$1+2=3$'], answer: '$3$' }], practice: [{ problemId: 'secret', statementText: 'paid content' }], quiz: [{ answer: 'private' }], studentId: 'private-id', correctCount: 15 };
function worker() {
  const handlers = {}, calls = [], stores = new Map(); let online = true, payload = formula, status = 200;
  const key = req => new URL(typeof req === 'string' ? req : req.url, origin).href;
  function cache(name) {
    if (!stores.has(name)) stores.set(name, new Map());
    const store = stores.get(name);
    return { match: async req => store.get(key(req))?.clone(), put: async (req, res) => { calls.push(['put', key(req)]); store.set(key(req), res.clone()); }, add: async req => { calls.push(['add', key(req)]); store.set(key(req), new Response('fallback')); }, keys: async () => [...store.keys()].map(url => ({ url })), delete: async req => store.delete(key(req)) };
  }
  const caches = { open: async name => cache(name), keys: async () => [...stores.keys()], delete: async name => { calls.push(['delete-cache', name]); return stores.delete(name); }, match: async (req, options) => options?.cacheName ? cache(options.cacheName).match(req) : [...stores.values()].map(store => store.get(key(req))).find(Boolean)?.clone() };
  const self = { location: { origin, href: origin + '/sw.js?api=' + encodeURIComponent(api) }, addEventListener: (name, fn) => { handlers[name] = fn; }, skipWaiting: async () => calls.push(['skipWaiting']) };
  vm.runInNewContext(fs.readFileSync(path.join(__dirname, '../public/sw.js'), 'utf8'), { self, caches, URL, Response, Date, fetch: async req => {
    const url = key(req); calls.push(['fetch', url]); if (!online) throw Error('offline');
    const res = url.startsWith(api) ? new Response(JSON.stringify(payload), { status, headers: { 'Content-Type': 'application/json' } }) : new Response('public html');
    Object.defineProperty(res, 'type', { value: url.startsWith(api) ? 'cors' : 'basic' });
    return res;
  } });
  async function dispatch(type, request, data) { const pending = []; let response; handlers[type]({ request, data, waitUntil: p => pending.push(p), respondWith: p => { response = p; } }); const result = await response; await Promise.all(pending); return result; }
  return { calls, stores, cache, dispatch, offline: () => { online = false; }, payload: (value, code = 200) => { payload = value; status = code; } };
}
const req = (url, mode = 'cors', method = 'GET') => ({ url: new URL(url, origin).href, mode, method });
test('installs public fallback and only purges old static namespace', async () => { const w = worker(); await w.cache('pi-public-static-v1').add('/old'); await w.cache('other-app-cache').add('/other'); await w.dispatch('install'); await w.dispatch('activate'); assert(w.stores.has('pi-public-static-v2')); assert(!w.stores.has('pi-public-static-v1')); assert(w.stores.has('other-app-cache')); assert(!w.calls.some(x => x[0] === 'skipWaiting')); });
test('static assets cache first, private HTML never writes a cache', async () => { const w = worker(); await w.dispatch('fetch', req('/_next/static/a.js')); await w.dispatch('fetch', req('/_next/static/a.js')); assert.equal(w.calls.filter(x => x[0] === 'fetch').length, 1); const writes = w.calls.filter(x => x[0] === 'put').length; await w.dispatch('fetch', req('/app/tests/exam', 'navigate')); assert.equal(w.calls.filter(x => x[0] === 'put').length, writes); });
test('offline examination gets only the generic public offline shell', async () => { const w = worker(); await w.dispatch('install'); w.offline(); const res = await w.dispatch('fetch', req('/app/tests/private', 'navigate')); assert.equal(await res.text(), 'public html'); });
test('private, modified, foreign, and lookalike API paths never intercepted', async () => { const w = worker(); for (const url of ['/api/me', '/api', '/app/exam?_rsc=1', '/uploads/student.png', api + '/formulas/my', api + '/formulas/review', api + '/formulas/review/due', api + '/formulas/stats', api + '/formulas/readiness', api + '/formulas/test-formula?studentId=secret', api + '/formulas%2Fmy', api + '/formulas-extra', 'https://evil.test/api/formulas/test-formula']) assert.equal(await w.dispatch('fetch', req(url)), undefined, url); assert.equal(await w.dispatch('fetch', req(api + '/formulas/test-formula', 'cors', 'POST')), undefined); assert.deepEqual(w.calls, []); });
test('catalog response persists only public math projection under token-free slug key', async () => { const w = worker(); const response = await w.dispatch('fetch', req(api + '/formulas/test-formula')); assert.equal((await response.json()).studentId, 'private-id', 'online response stays unchanged'); const saved = await w.cache('pi-public-formulas-v1').match('/offline/formula/test-formula.json'); const body = await saved.json(); for (const key of ['practice', 'quiz', 'studentId', 'correctCount', 'id']) assert.equal(key in body, false); assert.equal(body.examples[0].answer, '$3$'); assert(!JSON.stringify([...w.stores.get('pi-public-formulas-v1').keys()]).includes('api.example')); });
test('array catalog is supported, list refresh cannot erase detail', async () => { const w = worker(); await w.dispatch('fetch', req(api + '/formulas/test-formula')); w.payload([{ slug: formula.slug, title: formula.title, latex: formula.latex }]); await w.dispatch('fetch', req(api + '/formulas?q=sum')); const saved = await w.cache('pi-public-formulas-v1').match('/offline/formula/test-formula.json'); assert.equal((await saved.json()).explanation, formula.explanation); });
test('sections do not masquerade as formula records', async () => { const w = worker(); w.payload([{ slug: 'algebra', title: 'Алгебр', count: 42 }]); await w.dispatch('fetch', req(api + '/formulas/sections')); assert.equal(w.stores.get('pi-public-formulas-v1').size, 0); });
test('unauthorized/error responses never replace cached public content', async () => { const w = worker(); for (const code of [400, 401, 403, 500]) { w.payload({ ...formula, title: 'error data' }, code); await w.dispatch('fetch', req(api + '/formulas/test-formula')); } assert(!w.stores.has('pi-public-formulas-v1')); });
test('private API does not get replayed from any cache when offline', async () => { const w = worker(); await w.dispatch('fetch', req(api + '/formulas/test-formula')); w.offline(); assert.equal(await w.dispatch('fetch', req(api + '/formulas/my')), undefined); await assert.rejects(() => w.dispatch('fetch', req(api + '/formulas/test-formula')), /offline/); });
test('invalid or oversized payload never persisted', async () => { const w = worker(); for (const payload of [{ ...formula, slug: '../escape' }, { ...formula, extra: 'x'.repeat(2_000_001) }, null]) { w.payload(payload); await w.dispatch('fetch', req(api + '/formulas/test-formula')); } assert.equal(w.stores.get('pi-public-formulas-v1')?.size ?? 0, 0); });
test('static cache is bounded with offline fallbacks retained', async () => { const w = worker(); await w.dispatch('install'); for (let i = 0; i < 165; i++) await w.dispatch('fetch', req(`/_next/static/${i}.js`)); assert.equal(w.stores.get('pi-public-static-v2').size, 162); assert(await w.cache('pi-public-static-v2').match('/offline')); });
test('formula cache bounded at 500 records', async () => { const w = worker(); for (let i = 0; i < 6; i++) { w.payload(Array.from({ length: 100 }, (_, j) => ({ ...formula, slug: `formula-${i * 100 + j}` }))); await w.dispatch('fetch', req(api + '/formulas')); } assert.equal(w.stores.get('pi-public-formulas-v1').size, 500); });
test('activation only occurs after explicit update request', async () => { const w = worker(); await w.dispatch('message', undefined, { type: 'unknown' }); assert.equal(w.calls.length, 0); await w.dispatch('message', undefined, { type: 'PI_ACTIVATE_UPDATE' }); assert.deepEqual(w.calls, [['skipWaiting']]); });
